flowchart TD

    A["Gérer les catégories"]
    
    B["Tâche 1 : cree le MCD"]
    
    C["Tâche 2 : Creer base de donnees"]
    
    D["Tâche 3 : cree l'API (CRUD)"]

    E["Tâche 4 :<br>Cree formulaire HTML"]
    
    F["Tâche 5 :<br>Connecter le<br>formulaire à l'API"]
    
    G["Tâche 6 : Tester"]
    
    H["Tâche 7 : valider"]


    A --> B
    B --> C
    C --> D
    C --> E
    D --> F
    E --> F
    F --> G
    G --> H

