flowchart TD

    A["Gérer les catégories"]
    
    B["Tâche 1 : cree le MCD"]
    
    C["Tâche 2 : Creer base de donnees"]
    
    D["Tâche 3 : cree l'API (CRUD)"]

    E["Tâche 4 :<br>Connecter le<br>formulaire à l'API"]
    
    F["Tâche 4 :<br>Connecter le<br>formulaire à l'API"]
    
    G["Tâche 5 : Tester et<br>valider"]

    A --> B
    B --> C
    C --> D
    C --> E
    D --> F
    E --> F
    F --> G

